//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fatec.AAP4.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public cliente()
        {
            this.pedido = new HashSet<pedido>();
        }
    
        public int idCliente { get; set; }
        public string razaosocial { get; set; }
        public string cnpj { get; set; }
        public string incricao_estadual { get; set; }
        public string endereco { get; set; }
        public string bairro { get; set; }
        public string cidade { get; set; }
        public string uf { get; set; }
        public string telefone { get; set; }
        public string email { get; set; }
        public string contato { get; set; }
    
        public virtual ICollection<pedido> pedido { get; set; }
    }
}
