//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fatec.AAP4.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contas_receber
    {
        public int idContas_Receber { get; set; }
        public int idPedido { get; set; }
        public int id_planocontas { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
        public Nullable<System.DateTime> data_recebimento { get; set; }
        public string status { get; set; }
        public string forma_pagamento { get; set; }
    
        public virtual plano_contas plano_contas { get; set; }
        public virtual pedido pedido { get; set; }
    }
}
