//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fatec.AAP4.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class dre
    {
        public dre()
        {
            this.plano_contas = new HashSet<plano_contas>();
        }
    [Display(Name = "Código")]
        public int id_dre { get; set; }
        [Display(Name = "Descrição")]
        public string nome_dre { get; set; }
    
        public virtual ICollection<plano_contas> plano_contas { get; set; }
    }
}
