//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fatec.AAP4.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class estoque_produtoacabado
    {
        public int id_estoque_prodacab { get; set; }
        public int id_produto { get; set; }
        public int id_planocontas { get; set; }
        public Nullable<System.DateTime> data_fabricacao { get; set; }
        public Nullable<System.DateTime> data_estocagem { get; set; }
        public Nullable<int> quant_minima { get; set; }
        public Nullable<int> quant_maxima { get; set; }
        public Nullable<int> quant_atual { get; set; }
    
        public virtual plano_contas plano_contas { get; set; }
        public virtual produto produto { get; set; }
    }
}
