//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fatec.AAP4.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class estoque_materiaprima
    {

        [Display(Name = "Código no Estoque")]
        public int id_estoque_matprima { get; set; }
        [Display(Name = "Código Matéria-Prima")]
        public int id_matprima { get; set; }
        [Display(Name = "Código Plano Contas")]
        public int id_planocontas { get; set; }
        [Display(Name = "Data Estocagem")]
        public Nullable<System.DateTime> data_estocagem { get; set; }
        [Display(Name = "Quantidade minima")]
        public Nullable<int> quant_minima { get; set; }
        [Display(Name = "Quantidade máxima")]
        public Nullable<int> quant_maxima { get; set; }
        [Display(Name = "Quantidade Atual")]
        public Nullable<int> quant_atual { get; set; }
        [Display(Name = "Adicionar")]
        public Nullable<int> quant_adicionada { get; set; }
    
        public virtual plano_contas plano_contas { get; set; }
        public virtual materia_prima materia_prima { get; set; }
    }
}
