//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fatec.AAP4.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fornecedor
    {
        public fornecedor()
        {
            this.contas_pagar = new HashSet<contas_pagar>();
            this.fornece_materiaprima = new HashSet<fornece_materiaprima>();
        }
    
        public int id_fornecedor { get; set; }
        public string cnpj { get; set; }
        public string inscricao_estadual { get; set; }
        public string endereco { get; set; }
        public string bairro { get; set; }
        public string cidade { get; set; }
        public string uf { get; set; }
        public string telefone { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<contas_pagar> contas_pagar { get; set; }
        public virtual ICollection<fornece_materiaprima> fornece_materiaprima { get; set; }
    }
}
