//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fatec.AAP4.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mydbEntities : DbContext
    {
        public mydbEntities()
            : base("name=mydbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<contas_pagar> contas_pagar { get; set; }
        public virtual DbSet<contas_receber> contas_receber { get; set; }
        public virtual DbSet<dre> dre { get; set; }
        public virtual DbSet<estoque_materiaprima> estoque_materiaprima { get; set; }
        public virtual DbSet<estoque_produtoacabado> estoque_produtoacabado { get; set; }
        public virtual DbSet<fornece_materiaprima> fornece_materiaprima { get; set; }
        public virtual DbSet<fornecedor> fornecedor { get; set; }
        public virtual DbSet<item_pedido> item_pedido { get; set; }
        public virtual DbSet<materia_prima> materia_prima { get; set; }
        public virtual DbSet<outras_contas> outras_contas { get; set; }
        public virtual DbSet<pedido> pedido { get; set; }
        public virtual DbSet<plano_contas> plano_contas { get; set; }
        public virtual DbSet<produto> produto { get; set; }
    }
}
