//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fatec.AAP4.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class outras_contas
    {
        public int id_conta { get; set; }
        public string nome_conta { get; set; }
        public string descricao_conta { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
        public int Plano_Contas_id_planocontas { get; set; }
    
        public virtual plano_contas plano_contas { get; set; }
    }
}
