//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fatec.AAP4.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        public pedido()
        {
            this.contas_receber = new HashSet<contas_receber>();
        }
    
        public int idPedido { get; set; }
        public int idCliente { get; set; }
        public Nullable<System.DateTime> data_compra { get; set; }
        public Nullable<float> valor_total { get; set; }
        public int id_item_pedido_fk { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual ICollection<contas_receber> contas_receber { get; set; }
    }
}
