//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fatec.AAP4.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plano_contas
    {
        public plano_contas()
        {
            this.contas_pagar = new HashSet<contas_pagar>();
            this.contas_receber = new HashSet<contas_receber>();
            this.estoque_materiaprima = new HashSet<estoque_materiaprima>();
            this.estoque_produtoacabado = new HashSet<estoque_produtoacabado>();
            this.outras_contas = new HashSet<outras_contas>();
        }
    
        public int id_planocontas { get; set; }
        public int id_dre { get; set; }
        public string codigo_planocontas { get; set; }
        public string descricao_planocontas { get; set; }
    
        public virtual ICollection<contas_pagar> contas_pagar { get; set; }
        public virtual ICollection<contas_receber> contas_receber { get; set; }
        public virtual dre dre { get; set; }
        public virtual ICollection<estoque_materiaprima> estoque_materiaprima { get; set; }
        public virtual ICollection<estoque_produtoacabado> estoque_produtoacabado { get; set; }
        public virtual ICollection<outras_contas> outras_contas { get; set; }
    }
}
